name: careerguidance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  chat_gpt_sdk: ^3.0.7
  dash_chat_2: ^0.0.20

  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_gradient_app_bar: ^0.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  http: ^1.2.1
  pie_chart: ^5.0.0
  pdf: ^3.11.0
  path_provider: ^2.1.3
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
    - assets/home.jpg
    - assets/features.jpg
    - assets/info.jpg
    - assets/profile.jpg
    - assets/quiz.jpg
    - assets/career.avif
    - assets/tanishka.jpg
    - assets/20240504_140051.jpg
    - assets/kunal.jpg
